apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: codepusher-aws-terraform-environment
  description: The Codepusher AWS terraform environment template
  tags:
    - aws
    - terraform
spec:
  provider: aws
  owner: codepusher-team
  type: environment
  driver: 
    type: opentofu
    version: "1.17"
  parameters:
    - title: Environment Details
      required:
        - awsAccount
        - environmentName
        - Region
        - vpcCidr
        - owner
      properties:
        awsAccount:
          title: AWS Account
          type: array
          items:
            type: awsAccount
        Name:
          title: Environment Name
          type: string
        Region:
          title: AWS Region
          type: list     
          items:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
        vpcCidr:
          title: VPC CIDR
          type: string
        owner:
          title: Owner
          type: list
          items:
            type: teams
