apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: codepusher-aws-terraform-environment
  description: The Codepusher AWS terraform environment template
  tags:
    - aws
    - terraform
spec:
  provider: aws
  owner: codepusher-team
  type: environment
  driver: 
    type: opentofu
    version: "1.17"
  parameters:
    - title: Environment Details
      properties:
        awsAccount:
          title: AWS Account
          type: select
          items:
            type: accountId
            from: aws
        name:
          title: Environment Name
          type: string
        region:
          title: AWS Region
          type: select     
          items:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
        vpcCidr:
          title: VPC CIDR
          default: "10.0.0.0/16"
          type: string
        owner:
          title: Owner
          type: list
          items:
            type: teams
# the properties bellow will be passed implicitly
        roleArn:
          type: roleArn
          from: account
        stateBucket:
          type: stateBucket
          from: account
        stateTable:
          type: stateTable
          from: account