apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .serviceName }}
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: platform-dev
            namespace: platform-ai-dev
            path: environments/platform-dev
          # - env: platform-prod
          #   namespace: platform-ai-prod
          #   path: environments/platform-prod
  template:
    metadata:
      name: "{{ .serviceName }}-{{ env }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/{{ .githubOrg }}/{{ .serviceName }}-chart.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: "{{ env }}"
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true