repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: eks-module
        args: 
          - markdown 
          - table
          - --output-file README.md
          - ./terraform/eks/module
      - id: environment-module
        args: 
          - markdown 
          - table
          - --output-file README.md
          - ./terraform/environment/module
      - id: rds-module
        args: 
          - markdown 
          - table
          - --output-file README.md
          - ./terraform/rds/module