apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: golang-fiber-service
  displayName: Scaffold a new Golang Fiber service
  description: Quickly set up a new Golang project with the Fiber web framework.
  tags:
    - golang
    - fiber
    - service
    - api
spec:
  templateUrl: "https://github.com/codepusher-platform/codepusher-blueprints-aws/blob/main/github/golang/golang-fiber/template"
  provider: github
  owner: codepusher-team
  language: go
  type: service
  engine:
    type: github
    version: "1.0.0"
  steps:
    - title: Basic Information
      properties:
        serviceName:
          title: Service Name
          type: string
          description: "Name of the service."
        serviceDescription:
          title: Service Description
          type: string
          description: "A brief description of your service."
        project:
          title: Project Name
          type: string
          default: chip-labs
          description: "Name of the project that this service belongs to."
        sonarOrg:
          title: Sonar Organization
          type: string
          default: chip-labs
          description: "The Sonar organization to associate with this service."
        owner:
          title: Owner
          type: select
          items:
            type: list:team
        githubOrg:
          type: get:integration:githubOrg
          autofill: true