apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: python-fastapi-service
  displayName: Python+FastAPI service
  description: "A template for creating a Python FastAPI service."
  tags:
    - python
    - fastapi
    - service
    - api
spec:
  templateUrl: "https://github.com/codepusher-platform/codepusher-blueprints-aws/blob/main/github/python/python-fastapi/template"
  provider: github
  owner: codepusher-team
  language: python
  type: service
  engine:
    type: github
    version: "1.0.0"
  steps:
    - title: Basic Information
      properties:
        serviceName:
          title: Service Name
          type: string
          description: "Name of the service."
        serviceDescription:
          title: Service Description
          type: string
          description: "A brief description of your service."
        project:
          title: Project Name
          type: string
          default: chip-labs
          description: "Name of the project that this service belongs to."
        sonarOrg:
          title: Sonar Organization
          type: string
          default: chip-labs
          description: "The Sonar organization to associate with this service."
        owner:
          title: Owner
          type: select
          items:
            type: list:team
        githubOrg:
          type: get:integration:githubOrg
          autofill: true