apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: aws-fastapi-service
  displayName: Deploy FastAPI Service on AWS (EKS)
  description: A template to deploy a high-performance FastAPI service on Amazon EKS, with options for autoscaling, resource management, and API gateway integration.
  tags:
    - aws
    - eks
    - python
    - fastapi
    - service
    - api
spec:
  templateUrl: "https://github.com/codepusher-platform/codepusher-blueprints-aws/blob/main/github/python/python-fastapi/template"
  provider: aws
  owner: codepusher-team
  type: service
  engine:
    type: github
    version: "1.0.0"
  steps:
    - title: Basic Information
      properties:
        serviceName:
          title: Service Name (K8s)
          type: string
          description: "Unique name for your FastAPI service within Kubernetes (e.g., 'my-fastapi-app')."
        project:
          title: Project Name (GitHub)
          type: string
          description: "The name of your GitHub repository where your FastAPI project's code resides."
        owner:
          title: Owner
          type: select
          items:
            type: custom:teams
        githubOrg:
          type: custom:githubOrg
          autofill: true
