apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: nodejs-express-service
  displayName: Node.js Express Service
  description: "A template for creating a Node.js Express service."
  tags:
    - nodejs
    - express
    - service
    - api
spec:
  templateUrl: "https://github.com/codepusher-platform/codepusher-blueprints-aws/blob/main/github/nodejs/node-express/template"
  provider: github
  owner: codepusher-team
  language: nodejs
  type: service
  engine: 
    type: github
    version: "1.0.1"
  steps:
    - title: Basic Information
      properties:
        serviceName:
          title: Service Name
          type: string
          description: "Name of the service."
        project:
          title: Project Name
          type: string
          default: chip-labs
          description: "Name of the project that this service belongs to."
        sonarOrg:
          title: Sonar Organization
          type: string
          description: "The Sonar organization to associate with this service."
        owner:
          title: Owner
          type: select
          items:
            type: list:team
        serviceDescription:
          title: Service Description
          type: string
          description: "A brief description of your service."
        githubOrg:
          type: get:integration:githubOrg
          autofill: true

