apiVersion: codepusher.io/v1alpha1
kind: Service
metadata:
  name: "{{ .serviceName }}"
  description: "{{ .serviceDescription }}"
spec:
  language: python
  owner: "{{ .owner }}"
  project: "{{ .project }}"