apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: codepusher-aws-terraform-eks
  description: The Codepusher AWS terraform EKS template
  tags:
    - aws
    - terraform
    - eks
spec:
  owner: codepusher-team
  provider: aws
  type: eks
  driver: 
    type: opentofu
    version: "1.17"
  steps:
    - title: EKS Details
      properties:
        clusterName:
          title: Name
          type: string
        clusterVersion:
          title: Version
          type: string
        instanceTypes:
          title: Instance Types
          type: multi-select
          items:
            - "m6i.large"
            - "m5.large"
            - "m5n.large"
            - "m5zn.large"
        instanceClass:
          title: Instance Class
          type: select
          items:
            - "OnDemand"
            - "Spot"
        minNodes:
          title: Min Nodes
          type: int
        desiredNodes:
          title: Desired Nodes
          type: int
        maxNodes:
          title: Max Nodes
          type: int
        diskCapacity:
          title: Disk Capacity (GB)
          type: int  
        owner:
          title: Owner
          type: select
          items:
            type: custom:teams
        vpcId:
          type: custom:vpcId
          autofill: true
        vpcSubnetIds:
          type: custom:vpcSubnetIds
          autofill: true
        region:
          type: custom:region
          autofill: true
        environment:
          type: custom:name
          autofill: true
        roleArn:
          type: custom:roleArn
          autofill: true
        stateBucket:
          type: custom:stateBucket
          autofill: true
        stateTable:
          type: custom:stateTable
          autofill: true