apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: codepusher-aws-terraform-eks
  description: The Codepusher AWS terraform EKS template
  tags:
    - aws
    - terraform
    - eks
spec:
  owner: codepusher-team
  provider: aws
  type: eks
  driver: 
    type: opentofu
    version: "1.17"
  parameters:
    - title: EKS Details
      properties:
        clusterName:
          title: Name
          type: string
        clusterVersion:
          title: Version
          type: string
        instanceTypes:
          title: Instance Types
          type: multi-select
          items:
            - "m6i.large"
            - "m5.large"
            - "m5n.large"
            - "m5zn.large"
        instanceClass:
          title: Instance Class
          type: select
          items:
            - "OnDemand"
            - "Spot"
        minNodes:
          title: Min Nodes
          type: int
        desiredNodes:
          title: Desired Nodes
          type: int
        maxNodes:
          title: Max Nodes
          type: int
        diskCapacity:
          title: Disk Capacity (GB)
          type: int  
        owner:
          title: Owner
          type: select
          items:
            type: teams
            from: teams
# the properties bellow will be passed implicitly
        vpcId:
          type: vpcId
          from: environment
        vpcSubnetIds:
          type: vpcSubnetIds
          from: environment
        region:
          type: region
          from: environment
        environment:
          type: name
          from: environment
        roleArn:
          type: roleArn
          from: account
        stateBucket:
          type: stateBucket
          from: account
        stateTable:
          type: stateTable
          from: account